### ISSUE TITLE
Add property in test report

### ISSUE THREAD

**Issue by simjan** [qspin/qtaste#45] opened 2013-08-28 07:42 UTC
The idea is to allow the tester to add some parameter (key=value) in the report.

to do this, the following classes have to be updated:
TestResultImpl  (or maybe only the Result class....??? or in StepResultClass?????) :
- add a properties object to store the value
- add a method to add/remove/update/list properties

JythonTestScript :
- add a system to link the jython code with the result class. be carefull only the properties can be changed

Reporter:
- add all properties

**Comment by lvboque** [comment] 2015-05-26 12:08
This looks like a duplicate of #20

**Closed** 2015-05-26 12:08 UTC
Labels: category:kernel, priority:medium, type:new_feature
