### ISSUE TITLE
Documentation generation warning - function step is used in doStep() but not declared or not documented

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#173] opened 2015-05-06 10:07 UTC
QTaste complains with the error "Documentation generation warning - function step is used in doStep() but not declared or not documented" when a doStep is used with a function declared outside the same *.py file. The function is indeed deflined with the @step in an imported library.

**Comment by dergo** [comment] 2015-05-07 07:36
Duplicate of issue #92.

**Closed by dergo** 2015-05-07 07:36 UTC
